version: '3.7'

services:
  rpg-api-telegram:
    image: $AND_DOCKER_REGISTRY_NAME/$PROGECT-$APP:dev
    command: ./go-aut-registration-user-telegram
    tty: true
    container_name: $APP-dev
    ports:
      - 5001:5001
      - 5432:5432
      - 5012:5012
    restart: always
