version: '3.7'

services:
  rpg-api-telegram:
    build: ./
    command: ./rpg-api-telegram
    tty: true
    container_name: rpg-api-telegram
    ports:
      - 5001:5001
    depends_on:
      - db
    restart: always
