// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: protofiles/auth/auth.proto

package __auth_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendPhoneNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *SendPhoneNumberRequest) Reset() {
	*x = SendPhoneNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_auth_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPhoneNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPhoneNumberRequest) ProtoMessage() {}

func (x *SendPhoneNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_auth_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPhoneNumberRequest.ProtoReflect.Descriptor instead.
func (*SendPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SendPhoneNumberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendPhoneNumberRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type SendPhoneNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SendPhoneNumberResponse) Reset() {
	*x = SendPhoneNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_auth_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPhoneNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPhoneNumberResponse) ProtoMessage() {}

func (x *SendPhoneNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_auth_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPhoneNumberResponse.ProtoReflect.Descriptor instead.
func (*SendPhoneNumberResponse) Descriptor() ([]byte, []int) {
	return file_protofiles_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SendPhoneNumberResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_protofiles_auth_auth_proto protoreflect.FileDescriptor

var file_protofiles_auth_auth_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x61, 0x75, 0x74,
	0x68, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x75,
	0x74, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x16, 0x53, 0x65, 0x6e,
	0x64, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x31, 0x0a, 0x17, 0x53, 0x65, 0x6e,
	0x64, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x66, 0x0a, 0x06,
	0x47, 0x6f, 0x41, 0x75, 0x74, 0x68, 0x12, 0x5c, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofiles_auth_auth_proto_rawDescOnce sync.Once
	file_protofiles_auth_auth_proto_rawDescData = file_protofiles_auth_auth_proto_rawDesc
)

func file_protofiles_auth_auth_proto_rawDescGZIP() []byte {
	file_protofiles_auth_auth_proto_rawDescOnce.Do(func() {
		file_protofiles_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofiles_auth_auth_proto_rawDescData)
	})
	return file_protofiles_auth_auth_proto_rawDescData
}

var file_protofiles_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protofiles_auth_auth_proto_goTypes = []interface{}{
	(*SendPhoneNumberRequest)(nil),  // 0: auth_server.SendPhoneNumberRequest
	(*SendPhoneNumberResponse)(nil), // 1: auth_server.SendPhoneNumberResponse
}
var file_protofiles_auth_auth_proto_depIdxs = []int32{
	0, // 0: auth_server.GoAuth.SendPhoneNumber:input_type -> auth_server.SendPhoneNumberRequest
	1, // 1: auth_server.GoAuth.SendPhoneNumber:output_type -> auth_server.SendPhoneNumberResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protofiles_auth_auth_proto_init() }
func file_protofiles_auth_auth_proto_init() {
	if File_protofiles_auth_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofiles_auth_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPhoneNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_auth_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPhoneNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofiles_auth_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofiles_auth_auth_proto_goTypes,
		DependencyIndexes: file_protofiles_auth_auth_proto_depIdxs,
		MessageInfos:      file_protofiles_auth_auth_proto_msgTypes,
	}.Build()
	File_protofiles_auth_auth_proto = out.File
	file_protofiles_auth_auth_proto_rawDesc = nil
	file_protofiles_auth_auth_proto_goTypes = nil
	file_protofiles_auth_auth_proto_depIdxs = nil
}